/******************************************************************************
 * SELLQUIZ-LANGUAGE-WORKBENCH                                                *
 *                                                                            *
 * Copyright (c) 2019-2022 TH Köln                                            *
 * Author: Andreas Schwenk, contact@compiler-construction.com                 *
 *                                                                            *
 * Partly funded by: Digitale Hochschule NRW                                  *
 * https://www.dh.nrw/kooperationen/hm4mint.nrw-31                            *
 *                                                                            *
 * GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007                         *
 *                                                                            *
 * This library is licensed as described in LICENSE, which you should have    *
 * received as part of this distribution.                                     *
 *                                                                            *
 * This software is distributed on "AS IS" basis, WITHOUT WARRENTY OF ANY     *
 * KIND, either impressed or implied.                                         *
 ******************************************************************************/

export const symbols = [
    'sum',
    'prod',
    'xx',
    '@',
    'o+',
    'ox',
    'o.',
    '^^',
    '^^^',
    'vv',
    'vvv',
    'nn',
    'nnn',
    'uu',
    'uuu',
    'a/b',
    'a^b',
    'sqrt(x)',
    'root(x)(y)',
    'int',
    'oint',
    'del',
    'grad',
    '+-',
    'O/',
    'oo',
    'aleph',
    'abs(x)',
    'floor(x)',
    'ceil(x)',
    'norm(vecx)',
    '/_',
    '/_\\',
    'diamond',
    'square',
    'CC',
    'NN',
    'QQ',
    'RR',
    'ZZ',
    '"text"',
    '!=',
    '<',
    '>',
    '<=',
    '>=',
    '-<',
    '-<=',
    '>-',
    '>-=',
    'in',
    'notin',
    'sub',
    'sup',
    'sube',
    'supe',
    '-=',
    '~=',
    '~~',
    'prop',
    'neg',
    '=>',
    '<=>',
    'AA',
    'EE',
    '_|_',
    'TT',
    '|--',
    '|==',
    '{',
    '}',
    '(:',
    ':)',
    '<<',
    '>>',
    'uarr',
    'darr',
    '->',
    '>->',
    '->>',
    '>->>',
    '|->',
    'larr',
    'harr',
    'rArr',
    'lArr',
    'hArr',
    'hat x',
    'bar x',
    'ul x',
    'vec x',
    'tilde x',
    'dot x',
    'ddot x',
    'overset(x)(=)',
    'underset(x)(=)',
    'ubrace(x)',
    'obrace(x)',
    'color(red)(x)',
    'cancel(x)',
    'alpha',
    'beta',
    'gamma',
    'delta',
    'epsilon',
    'varepsilon',
    'zeta',
    'eta',
    'theta',
    'vartheta',
    'iota',
    'kappa',
    'lambda',
    'mu',
    'nu',
    'xi',
    'pi',
    'rho',
    'sigma',
    'tau',
    'upsilon',
    'phi',
    'varphi',
    'chi',
    'psi',
    'omega',
    'bb "Aa"',
    'bbb "Aa"',
    'cc "Aa"',
    'tt "Aa"',
    'fr "Aa"',
    'sf "Aa"',
    '[[a,b],[c,d]]',
    '((a),(b))',
    '[[a,b,|,c],[d,e,|,f]]',
    'lim_(n->oo) sum_(i=0)^n',
    'int_0^1 f(x) \\ dx',
    "f'(x)=dy/dx",
];
